#!/usr/bin/env python3
"""
cassette2vec_ML_v11_FINAL.py
============================
Cassette2Vec-EC v1.1 — Evaluation & Visualization Script

Generates all manuscript figures:
  • ROC curve                   → cassette2vec_v11_ROC_curve.png
  • Precision-Recall curve      → cassette2vec_v11_PR_curve.png
  • Score distribution boxplot  → cassette2vec_v11_boxplot.png
  • Confusion matrix            → cassette2vec_v11_confusion_matrix.png
  • Calibration curve           → cassette2vec_v11_calibration.png
  • SHAP beeswarm summary       → cassette2vec_v11_SHAP_summary.png

Usage (from repo root):
  python cassette2vec_ML_v11_FINAL.py

  # Or with custom paths:
  python cassette2vec_ML_v11_FINAL.py \\
      --model    data/cassette2vec_v11_model.pkl \\
      --preds    data/cassette2vec_v11_predictions.csv \\
      --features data/cassette2vec_ML_features_v1_with_AMR_neighborhood.csv \\
      --outdir   figures/

NOTE: The features file must first be generated by running:
  python add_AMR_neighborhood_v1.py
  (input:  data/cassette2vec_ML_features_v1_with_mobility_load.csv)
  (output: data/cassette2vec_ML_features_v1_with_AMR_neighborhood.csv)

Requirements:
  pip install xgboost==2.0.3 shap==0.44.1 scikit-learn==1.4.2 \\
              pandas==2.2.1 matplotlib==3.8.3 seaborn==0.13.2 \\
              joblib==1.3.2 numpy==1.26.4

Authors: Rushikesh R. Lagad, Shakil Rafi, Aranyak Goswami
Repository: https://github.com/RushiLagad/Cassette2Vec (tag v1.1.0)
Zenodo DOI: https://doi.org/10.5281/zenodo.18529389
"""

# ============================================================
# REPRODUCIBILITY — fix all seeds before any other imports
# ============================================================
import random
import numpy as np
SEED = 42
random.seed(SEED)
np.random.seed(SEED)

# ============================================================
# STANDARD IMPORTS
# ============================================================
import argparse
import sys
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

from sklearn.metrics import (
    roc_curve,
    auc,
    precision_recall_curve,
    average_precision_score,
    confusion_matrix,
)

import shap


# ============================================================
# ARGUMENT PARSING
# ============================================================
def parse_args():
    # Default paths relative to the repo root (one level above this script)
    repo_root = Path(__file__).resolve().parent

    parser = argparse.ArgumentParser(
        description="Cassette2Vec v1.1 — Generate all evaluation figures"
    )
    parser.add_argument(
        "--model",
        type=Path,
        default=repo_root / "data" / "cassette2vec_v11_model.pkl",
        help="Path to trained XGBoost model (.pkl)",
    )
    parser.add_argument(
        "--preds",
        type=Path,
        default=repo_root / "data" / "cassette2vec_v11_predictions.csv",
        help="Path to predictions CSV (columns: true_label, pred_score)",
    )
    parser.add_argument(
        "--features",
        type=Path,
        default=repo_root / "data" / "cassette2vec_ML_features_v1_with_AMR_neighborhood.csv",
        help="Path to cassette feature matrix CSV (used for SHAP plot). "
             "Generate with add_AMR_neighborhood_v1.py first.",
    )
    parser.add_argument(
        "--outdir",
        type=Path,
        default=repo_root / "figures",
        help="Directory to save all output figures",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.5,
        help="Decision threshold for confusion matrix (default: 0.5)",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=300,
        help="DPI for saved figures (default: 300)",
    )
    return parser.parse_args()


# ============================================================
# HELPER — save figure
# ============================================================
def save_fig(outdir: Path, filename: str, dpi: int):
    outdir.mkdir(parents=True, exist_ok=True)
    out_path = outdir / filename
    plt.tight_layout()
    plt.savefig(out_path, dpi=dpi)
    plt.close()
    print(f"  [SAVED] {out_path}")


# ============================================================
# PLOT 1 — ROC CURVE
# ============================================================
def plot_roc(y_true, y_pred, outdir, dpi):
    print("[PLOT] ROC curve...")
    fpr, tpr, _ = roc_curve(y_true, y_pred)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(6, 6))
    plt.plot(fpr, tpr, lw=2, color="#1f77b4",
             label=f"Cassette2Vec v1.1  (AUC = {roc_auc:.3f})")
    plt.plot([0, 1], [0, 1], "--", color="gray", lw=1)
    plt.xlabel("False Positive Rate", fontsize=12)
    plt.ylabel("True Positive Rate", fontsize=12)
    plt.title("Cassette2Vec v1.1 – ROC Curve", fontsize=13)
    plt.legend(fontsize=11)
    save_fig(outdir, "cassette2vec_v11_ROC_curve.png", dpi)


# ============================================================
# PLOT 2 — PRECISION-RECALL CURVE
# ============================================================
def plot_pr(y_true, y_pred, outdir, dpi):
    print("[PLOT] Precision-Recall curve...")
    precision, recall, _ = precision_recall_curve(y_true, y_pred)
    pr_auc = average_precision_score(y_true, y_pred)

    plt.figure(figsize=(6, 6))
    plt.plot(recall, precision, lw=2, color="#2ca02c",
             label=f"Cassette2Vec v1.1  (AP = {pr_auc:.3f})")
    plt.xlabel("Recall", fontsize=12)
    plt.ylabel("Precision", fontsize=12)
    plt.title("Cassette2Vec v1.1 – Precision-Recall Curve", fontsize=13)
    plt.legend(fontsize=11)
    save_fig(outdir, "cassette2vec_v11_PR_curve.png", dpi)


# ============================================================
# PLOT 3 — SCORE DISTRIBUTION BOXPLOT
# ============================================================
def plot_boxplot(pred_df, outdir, dpi):
    print("[PLOT] Score distribution boxplot...")
    bp_df = pred_df.copy()
    bp_df["group"] = bp_df["true_label"].replace({0: "commensal", 1: "pathogenic"})

    plt.figure(figsize=(6, 6))
    sns.boxplot(data=bp_df, x="group", y="pred_score", palette="Set2",
                order=["commensal", "pathogenic"])
    sns.stripplot(data=bp_df, x="group", y="pred_score",
                  color="black", alpha=0.20, size=2,
                  order=["commensal", "pathogenic"])
    plt.xlabel("Group", fontsize=12)
    plt.ylabel("Predicted Score", fontsize=12)
    plt.title("Cassette2Vec v1.1 – Score Distribution", fontsize=13)
    save_fig(outdir, "cassette2vec_v11_boxplot.png", dpi)


# ============================================================
# PLOT 4 — CONFUSION MATRIX
# ============================================================
def plot_confusion(y_true, y_pred, threshold, outdir, dpi):
    print(f"[PLOT] Confusion matrix (threshold = {threshold})...")
    y_bin = (y_pred >= threshold).astype(int)
    cm = confusion_matrix(y_true, y_bin)

    plt.figure(figsize=(5, 4))
    sns.heatmap(
        cm, annot=True, fmt="d", cmap="Blues",
        xticklabels=["Commensal", "Pathogenic"],
        yticklabels=["Commensal", "Pathogenic"],
    )
    plt.xlabel("Predicted", fontsize=11)
    plt.ylabel("True", fontsize=11)
    plt.title(f"Cassette2Vec v1.1 – Confusion Matrix\n(threshold = {threshold})",
              fontsize=12)
    save_fig(outdir, "cassette2vec_v11_confusion_matrix.png", dpi)


# ============================================================
# PLOT 5 — CALIBRATION CURVE (manual, no sklearn dependency)
# ============================================================
def plot_calibration(y_true, y_pred, outdir, dpi, n_bins=10):
    print("[PLOT] Calibration curve...")
    bins = np.linspace(0, 1, n_bins + 1)
    bin_ids = np.digitize(y_pred, bins) - 1
    bin_ids = np.clip(bin_ids, 0, n_bins - 1)

    bin_pred, bin_true = [], []
    for b in range(n_bins):
        idx = bin_ids == b
        if idx.sum() == 0:
            continue
        bin_pred.append(np.mean(y_pred[idx]))
        bin_true.append(np.mean(y_true[idx]))

    plt.figure(figsize=(6, 6))
    plt.plot([0, 1], [0, 1], "--", color="gray", lw=1, label="Perfect calibration")
    plt.plot(bin_pred, bin_true, "-o", lw=2, color="#d62728",
             label="Cassette2Vec v1.1")
    plt.xlabel("Predicted Probability", fontsize=12)
    plt.ylabel("Observed Frequency", fontsize=12)
    plt.title("Cassette2Vec v1.1 – Calibration Curve", fontsize=13)
    plt.legend(fontsize=11)
    save_fig(outdir, "cassette2vec_v11_calibration.png", dpi)


# ============================================================
# PLOT 6 — SHAP BEESWARM SUMMARY
# ============================================================
def plot_shap(model, features_path: Path, outdir: Path, dpi: int):
    print("[PLOT] SHAP summary plot (this may take 1–2 minutes)...")

    if not features_path.exists():
        print(
            f"  [SKIP] Feature file not found: {features_path}\n"
            "         Run add_AMR_neighborhood_v1.py first to generate it.\n"
            "         SHAP plot will be skipped."
        )
        return

    features_df = pd.read_csv(features_path, low_memory=False)

    # Drop label and identifier columns — keep only model input features
    drop_cols = [
        "is_pathogenic", "true_label", "pred_score",
        "genome_id", "contig", "GI_ID", "gene_id",      # identifiers
        "eggNOG_class", "pathway", "cluster_id",          # reserved/unpopulated
    ]
    features_df = features_df.drop(columns=drop_cols, errors="ignore")

    # Convert any remaining object columns to numeric category codes
    for col in features_df.select_dtypes(include="object").columns:
        features_df[col] = features_df[col].astype("category").cat.codes

    # Fill NaN (required by XGBoost SHAP)
    features_df = features_df.fillna(0)

    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(features_df)

    # XGBoost binary classifier may return list [neg_class, pos_class]
    if isinstance(shap_values, list):
        shap_values = shap_values[1]

    plt.figure(figsize=(10, 7))
    shap.summary_plot(shap_values, features_df, show=False, max_display=15)
    plt.title("Cassette2Vec v1.1 – SHAP Feature Importance", fontsize=13, pad=14)
    save_fig(outdir, "cassette2vec_v11_SHAP_summary.png", dpi)


# ============================================================
# PRINT SUMMARY METRICS
# ============================================================
def print_metrics(y_true, y_pred, threshold):
    fpr, tpr, _ = roc_curve(y_true, y_pred)
    roc_auc = auc(fpr, tpr)
    ap = average_precision_score(y_true, y_pred)
    brier = float(np.mean((y_pred - y_true) ** 2))
    y_bin = (y_pred >= threshold).astype(int)
    cm = confusion_matrix(y_true, y_bin)
    tn, fp, fn, tp = cm.ravel()

    print("\n" + "=" * 52)
    print("  Cassette2Vec v1.1 — Performance Summary")
    print("=" * 52)
    print(f"  ROC-AUC     : {roc_auc:.4f}")
    print(f"  Avg Precision: {ap:.4f}")
    print(f"  Brier Score : {brier:.4f}")
    print(f"  Threshold   : {threshold}")
    print(f"  TP={tp}  FP={fp}  TN={tn}  FN={fn}")
    print("=" * 52 + "\n")


# ============================================================
# MAIN
# ============================================================
def main():
    args = parse_args()

    # ── Load model ──────────────────────────────────────────
    print(f"\n[INFO] Loading model from: {args.model}")
    if not args.model.exists():
        sys.exit(f"ERROR: Model file not found: {args.model}")
    model = joblib.load(args.model)

    # ── Load predictions ────────────────────────────────────
    print(f"[INFO] Loading predictions from: {args.preds}")
    if not args.preds.exists():
        sys.exit(f"ERROR: Predictions file not found: {args.preds}")
    pred_df = pd.read_csv(args.preds)

    required = {"true_label", "pred_score"}
    missing = required - set(pred_df.columns)
    if missing:
        sys.exit(f"ERROR: Missing columns in predictions file: {missing}\n"
                 f"       Found: {pred_df.columns.tolist()}")

    y_true = pred_df["true_label"].astype(int).values
    y_pred = pred_df["pred_score"].astype(float).values

    print(f"[INFO] Loaded {len(pred_df):,} rows  "
          f"({y_true.sum():,} pathogenic / {(y_true==0).sum():,} commensal)")

    # ── Print metrics ────────────────────────────────────────
    print_metrics(y_true, y_pred, args.threshold)

    # ── Generate all plots ───────────────────────────────────
    plot_roc(y_true, y_pred, args.outdir, args.dpi)
    plot_pr(y_true, y_pred, args.outdir, args.dpi)
    plot_boxplot(pred_df, args.outdir, args.dpi)
    plot_confusion(y_true, y_pred, args.threshold, args.outdir, args.dpi)
    plot_calibration(y_true, y_pred, args.outdir, args.dpi)
    plot_shap(model, args.features, args.outdir, args.dpi)

    print("\n" + "=" * 52)
    print("  ALL FIGURES GENERATED SUCCESSFULLY")
    print(f"  Output directory: {args.outdir.resolve()}")
    print("=" * 52 + "\n")


if __name__ == "__main__":
    main()
